# Generated by Django 5.2.8 on 2025-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
