# Generated by Django 5.2.8 on 2025-12-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_has_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='has_read',
        ),
        migrations.AddField(
            model_name='book',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
